using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class characterController : MonoBehaviour
{
    public float speed = 1.0f;
    private Rigidbody2D r2d;
    private Animator _animator;
    private Vector3 charPos; //karakter pozisyonu
    private SpriteRenderer _spriteRenderer; //karakterin yönü için
    [SerializeField] private GameObject _camera;
    private int sayi;

    void Start()
    {
        _spriteRenderer = GetComponent<SpriteRenderer>(); //caching SpriteRenderer
        r2d = GetComponent<Rigidbody2D>();  //caching r2d
        _animator = GetComponent<Animator>();  //caching anim
        charPos = transform.position;
        sayi = 1;
    }

    private void FixedUpdate() 
    {
        sayi = 2;
    }
   
    void Update() // per frame
    {
        charPos = new Vector3(charPos.x + (Input.GetAxis("Horizontal") * speed * Time.deltaTime), charPos.y); // deltatime her bir frame arasýndaki zamaný tutuyor,
        //frame ler arasý geçiþ yaparken aradaki fark kadar hýzla çarpým yapýp pozisyonu deðiþtirir
        transform.position = charPos; //hesapladýðým pozisyon karakterime iþlensin
        if (Input.GetAxis("Horizontal") == 0)
        {
            _animator.SetFloat("speed", 0.0f);
        }
        else
        {
            _animator.SetFloat("speed", 1.0f);
        }

        if (Input.GetAxis("Horizontal") > 0.01f)
        {
            _spriteRenderer.flipX = false;
        }
        else if (Input.GetAxis("Horizontal") < -0.01f)
        {
            _spriteRenderer.flipX = true;
        }
        sayi = 3;
    }

    private void LateUpdate()
    {
        sayi = 4;
    }

}
